// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/match.proto

package generalsstats

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	timestamp "github.com/golang/protobuf/ptypes/timestamp"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type General int32

const (
	General_USA      General = 0
	General_AIR      General = 1
	General_LASER    General = 2
	General_SUPER    General = 3
	General_CHINA    General = 4
	General_NUKE     General = 5
	General_TANK     General = 6
	General_INFANTRY General = 7
	General_GLA      General = 8
	General_TOXIN    General = 9
	General_STEALTH  General = 10
	General_DEMO     General = 11
)

var General_name = map[int32]string{
	0:  "USA",
	1:  "AIR",
	2:  "LASER",
	3:  "SUPER",
	4:  "CHINA",
	5:  "NUKE",
	6:  "TANK",
	7:  "INFANTRY",
	8:  "GLA",
	9:  "TOXIN",
	10: "STEALTH",
	11: "DEMO",
}

var General_value = map[string]int32{
	"USA":      0,
	"AIR":      1,
	"LASER":    2,
	"SUPER":    3,
	"CHINA":    4,
	"NUKE":     5,
	"TANK":     6,
	"INFANTRY": 7,
	"GLA":      8,
	"TOXIN":    9,
	"STEALTH":  10,
	"DEMO":     11,
}

func (x General) String() string {
	return proto.EnumName(General_name, int32(x))
}

func (General) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{0}
}

type Faction int32

const (
	Faction_ANYUSA   Faction = 0
	Faction_ANYCHINA Faction = 1
	Faction_ANYGLA   Faction = 2
)

var Faction_name = map[int32]string{
	0: "ANYUSA",
	1: "ANYCHINA",
	2: "ANYGLA",
}

var Faction_value = map[string]int32{
	"ANYUSA":   0,
	"ANYCHINA": 1,
	"ANYGLA":   2,
}

func (x Faction) String() string {
	return proto.EnumName(Faction_name, int32(x))
}

func (Faction) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{1}
}

type Team int32

const (
	Team_NONE  Team = 0
	Team_ONE   Team = 1
	Team_TWO   Team = 2
	Team_THREE Team = 3
	Team_FOUR  Team = 4
)

var Team_name = map[int32]string{
	0: "NONE",
	1: "ONE",
	2: "TWO",
	3: "THREE",
	4: "FOUR",
}

var Team_value = map[string]int32{
	"NONE":  0,
	"ONE":   1,
	"TWO":   2,
	"THREE": 3,
	"FOUR":  4,
}

func (x Team) String() string {
	return proto.EnumName(Team_name, int32(x))
}

func (Team) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{2}
}

type Player struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	General              General  `protobuf:"varint,2,opt,name=general,proto3,enum=matches.General" json:"general,omitempty"`
	Team                 Team     `protobuf:"varint,3,opt,name=team,proto3,enum=matches.Team" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Player) Reset()         { *m = Player{} }
func (m *Player) String() string { return proto.CompactTextString(m) }
func (*Player) ProtoMessage()    {}
func (*Player) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{0}
}

func (m *Player) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Player.Unmarshal(m, b)
}
func (m *Player) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Player.Marshal(b, m, deterministic)
}
func (m *Player) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Player.Merge(m, src)
}
func (m *Player) XXX_Size() int {
	return xxx_messageInfo_Player.Size(m)
}
func (m *Player) XXX_DiscardUnknown() {
	xxx_messageInfo_Player.DiscardUnknown(m)
}

var xxx_messageInfo_Player proto.InternalMessageInfo

func (m *Player) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Player) GetGeneral() General {
	if m != nil {
		return m.General
	}
	return General_USA
}

func (m *Player) GetTeam() Team {
	if m != nil {
		return m.Team
	}
	return Team_NONE
}

type MatchInfo struct {
	Id                   int64                `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Timestamp            *timestamp.Timestamp `protobuf:"bytes,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Map                  string               `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	WinningTeam          Team                 `protobuf:"varint,4,opt,name=winning_team,json=winningTeam,proto3,enum=matches.Team" json:"winning_team,omitempty"`
	Players              []*Player            `protobuf:"bytes,5,rep,name=players,proto3" json:"players,omitempty"`
	DurationMinutes      float64              `protobuf:"fixed64,6,opt,name=duration_minutes,json=durationMinutes,proto3" json:"duration_minutes,omitempty"`
	Filename             string               `protobuf:"bytes,7,opt,name=filename,proto3" json:"filename,omitempty"`
	Incomplete           string               `protobuf:"bytes,8,opt,name=incomplete,proto3" json:"incomplete,omitempty"`
	Notes                string               `protobuf:"bytes,9,opt,name=notes,proto3" json:"notes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MatchInfo) Reset()         { *m = MatchInfo{} }
func (m *MatchInfo) String() string { return proto.CompactTextString(m) }
func (*MatchInfo) ProtoMessage()    {}
func (*MatchInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{1}
}

func (m *MatchInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchInfo.Unmarshal(m, b)
}
func (m *MatchInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchInfo.Marshal(b, m, deterministic)
}
func (m *MatchInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchInfo.Merge(m, src)
}
func (m *MatchInfo) XXX_Size() int {
	return xxx_messageInfo_MatchInfo.Size(m)
}
func (m *MatchInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchInfo.DiscardUnknown(m)
}

var xxx_messageInfo_MatchInfo proto.InternalMessageInfo

func (m *MatchInfo) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *MatchInfo) GetTimestamp() *timestamp.Timestamp {
	if m != nil {
		return m.Timestamp
	}
	return nil
}

func (m *MatchInfo) GetMap() string {
	if m != nil {
		return m.Map
	}
	return ""
}

func (m *MatchInfo) GetWinningTeam() Team {
	if m != nil {
		return m.WinningTeam
	}
	return Team_NONE
}

func (m *MatchInfo) GetPlayers() []*Player {
	if m != nil {
		return m.Players
	}
	return nil
}

func (m *MatchInfo) GetDurationMinutes() float64 {
	if m != nil {
		return m.DurationMinutes
	}
	return 0
}

func (m *MatchInfo) GetFilename() string {
	if m != nil {
		return m.Filename
	}
	return ""
}

func (m *MatchInfo) GetIncomplete() string {
	if m != nil {
		return m.Incomplete
	}
	return ""
}

func (m *MatchInfo) GetNotes() string {
	if m != nil {
		return m.Notes
	}
	return ""
}

type Matches struct {
	Matches              []*MatchInfo `protobuf:"bytes,1,rep,name=matches,proto3" json:"matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *Matches) Reset()         { *m = Matches{} }
func (m *Matches) String() string { return proto.CompactTextString(m) }
func (*Matches) ProtoMessage()    {}
func (*Matches) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{2}
}

func (m *Matches) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Matches.Unmarshal(m, b)
}
func (m *Matches) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Matches.Marshal(b, m, deterministic)
}
func (m *Matches) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Matches.Merge(m, src)
}
func (m *Matches) XXX_Size() int {
	return xxx_messageInfo_Matches.Size(m)
}
func (m *Matches) XXX_DiscardUnknown() {
	xxx_messageInfo_Matches.DiscardUnknown(m)
}

var xxx_messageInfo_Matches proto.InternalMessageInfo

func (m *Matches) GetMatches() []*MatchInfo {
	if m != nil {
		return m.Matches
	}
	return nil
}

type WinLoss struct {
	Wins                 int32    `protobuf:"varint,1,opt,name=wins,proto3" json:"wins,omitempty"`
	Losses               int32    `protobuf:"varint,2,opt,name=losses,proto3" json:"losses,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *WinLoss) Reset()         { *m = WinLoss{} }
func (m *WinLoss) String() string { return proto.CompactTextString(m) }
func (*WinLoss) ProtoMessage()    {}
func (*WinLoss) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{3}
}

func (m *WinLoss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_WinLoss.Unmarshal(m, b)
}
func (m *WinLoss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_WinLoss.Marshal(b, m, deterministic)
}
func (m *WinLoss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_WinLoss.Merge(m, src)
}
func (m *WinLoss) XXX_Size() int {
	return xxx_messageInfo_WinLoss.Size(m)
}
func (m *WinLoss) XXX_DiscardUnknown() {
	xxx_messageInfo_WinLoss.DiscardUnknown(m)
}

var xxx_messageInfo_WinLoss proto.InternalMessageInfo

func (m *WinLoss) GetWins() int32 {
	if m != nil {
		return m.Wins
	}
	return 0
}

func (m *WinLoss) GetLosses() int32 {
	if m != nil {
		return m.Losses
	}
	return 0
}

type GeneralWL struct {
	General              General  `protobuf:"varint,1,opt,name=general,proto3,enum=matches.General" json:"general,omitempty"`
	WinLoss              *WinLoss `protobuf:"bytes,2,opt,name=win_loss,json=winLoss,proto3" json:"win_loss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralWL) Reset()         { *m = GeneralWL{} }
func (m *GeneralWL) String() string { return proto.CompactTextString(m) }
func (*GeneralWL) ProtoMessage()    {}
func (*GeneralWL) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{4}
}

func (m *GeneralWL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralWL.Unmarshal(m, b)
}
func (m *GeneralWL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralWL.Marshal(b, m, deterministic)
}
func (m *GeneralWL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralWL.Merge(m, src)
}
func (m *GeneralWL) XXX_Size() int {
	return xxx_messageInfo_GeneralWL.Size(m)
}
func (m *GeneralWL) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralWL.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralWL proto.InternalMessageInfo

func (m *GeneralWL) GetGeneral() General {
	if m != nil {
		return m.General
	}
	return General_USA
}

func (m *GeneralWL) GetWinLoss() *WinLoss {
	if m != nil {
		return m.WinLoss
	}
	return nil
}

type PlayerStat struct {
	PlayerName           string                  `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Stats                []*GeneralWL            `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	FactionStats         []*PlayerStat_FactionWL `protobuf:"bytes,3,rep,name=faction_stats,json=factionStats,proto3" json:"faction_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *PlayerStat) Reset()         { *m = PlayerStat{} }
func (m *PlayerStat) String() string { return proto.CompactTextString(m) }
func (*PlayerStat) ProtoMessage()    {}
func (*PlayerStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{5}
}

func (m *PlayerStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStat.Unmarshal(m, b)
}
func (m *PlayerStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStat.Marshal(b, m, deterministic)
}
func (m *PlayerStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStat.Merge(m, src)
}
func (m *PlayerStat) XXX_Size() int {
	return xxx_messageInfo_PlayerStat.Size(m)
}
func (m *PlayerStat) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStat.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStat proto.InternalMessageInfo

func (m *PlayerStat) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *PlayerStat) GetStats() []*GeneralWL {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *PlayerStat) GetFactionStats() []*PlayerStat_FactionWL {
	if m != nil {
		return m.FactionStats
	}
	return nil
}

type PlayerStat_FactionWL struct {
	Faction              Faction  `protobuf:"varint,1,opt,name=faction,proto3,enum=matches.Faction" json:"faction,omitempty"`
	WinLoss              *WinLoss `protobuf:"bytes,2,opt,name=win_loss,json=winLoss,proto3" json:"win_loss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlayerStat_FactionWL) Reset()         { *m = PlayerStat_FactionWL{} }
func (m *PlayerStat_FactionWL) String() string { return proto.CompactTextString(m) }
func (*PlayerStat_FactionWL) ProtoMessage()    {}
func (*PlayerStat_FactionWL) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{5, 0}
}

func (m *PlayerStat_FactionWL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStat_FactionWL.Unmarshal(m, b)
}
func (m *PlayerStat_FactionWL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStat_FactionWL.Marshal(b, m, deterministic)
}
func (m *PlayerStat_FactionWL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStat_FactionWL.Merge(m, src)
}
func (m *PlayerStat_FactionWL) XXX_Size() int {
	return xxx_messageInfo_PlayerStat_FactionWL.Size(m)
}
func (m *PlayerStat_FactionWL) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStat_FactionWL.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStat_FactionWL proto.InternalMessageInfo

func (m *PlayerStat_FactionWL) GetFaction() Faction {
	if m != nil {
		return m.Faction
	}
	return Faction_ANYUSA
}

func (m *PlayerStat_FactionWL) GetWinLoss() *WinLoss {
	if m != nil {
		return m.WinLoss
	}
	return nil
}

type PlayerStats struct {
	PlayerStats          []*PlayerStat `protobuf:"bytes,1,rep,name=player_stats,json=playerStats,proto3" json:"player_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *PlayerStats) Reset()         { *m = PlayerStats{} }
func (m *PlayerStats) String() string { return proto.CompactTextString(m) }
func (*PlayerStats) ProtoMessage()    {}
func (*PlayerStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{6}
}

func (m *PlayerStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlayerStats.Unmarshal(m, b)
}
func (m *PlayerStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlayerStats.Marshal(b, m, deterministic)
}
func (m *PlayerStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlayerStats.Merge(m, src)
}
func (m *PlayerStats) XXX_Size() int {
	return xxx_messageInfo_PlayerStats.Size(m)
}
func (m *PlayerStats) XXX_DiscardUnknown() {
	xxx_messageInfo_PlayerStats.DiscardUnknown(m)
}

var xxx_messageInfo_PlayerStats proto.InternalMessageInfo

func (m *PlayerStats) GetPlayerStats() []*PlayerStat {
	if m != nil {
		return m.PlayerStats
	}
	return nil
}

type GeneralStat struct {
	General              General                 `protobuf:"varint,1,opt,name=general,proto3,enum=matches.General" json:"general,omitempty"`
	Stats                []*GeneralStat_PlayerWL `protobuf:"bytes,2,rep,name=stats,proto3" json:"stats,omitempty"`
	Total                *WinLoss                `protobuf:"bytes,3,opt,name=total,proto3" json:"total,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                `json:"-"`
	XXX_unrecognized     []byte                  `json:"-"`
	XXX_sizecache        int32                   `json:"-"`
}

func (m *GeneralStat) Reset()         { *m = GeneralStat{} }
func (m *GeneralStat) String() string { return proto.CompactTextString(m) }
func (*GeneralStat) ProtoMessage()    {}
func (*GeneralStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{7}
}

func (m *GeneralStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralStat.Unmarshal(m, b)
}
func (m *GeneralStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralStat.Marshal(b, m, deterministic)
}
func (m *GeneralStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralStat.Merge(m, src)
}
func (m *GeneralStat) XXX_Size() int {
	return xxx_messageInfo_GeneralStat.Size(m)
}
func (m *GeneralStat) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralStat.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralStat proto.InternalMessageInfo

func (m *GeneralStat) GetGeneral() General {
	if m != nil {
		return m.General
	}
	return General_USA
}

func (m *GeneralStat) GetStats() []*GeneralStat_PlayerWL {
	if m != nil {
		return m.Stats
	}
	return nil
}

func (m *GeneralStat) GetTotal() *WinLoss {
	if m != nil {
		return m.Total
	}
	return nil
}

type GeneralStat_PlayerWL struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	WinLoss              *WinLoss `protobuf:"bytes,2,opt,name=win_loss,json=winLoss,proto3" json:"win_loss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GeneralStat_PlayerWL) Reset()         { *m = GeneralStat_PlayerWL{} }
func (m *GeneralStat_PlayerWL) String() string { return proto.CompactTextString(m) }
func (*GeneralStat_PlayerWL) ProtoMessage()    {}
func (*GeneralStat_PlayerWL) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{7, 0}
}

func (m *GeneralStat_PlayerWL) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralStat_PlayerWL.Unmarshal(m, b)
}
func (m *GeneralStat_PlayerWL) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralStat_PlayerWL.Marshal(b, m, deterministic)
}
func (m *GeneralStat_PlayerWL) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralStat_PlayerWL.Merge(m, src)
}
func (m *GeneralStat_PlayerWL) XXX_Size() int {
	return xxx_messageInfo_GeneralStat_PlayerWL.Size(m)
}
func (m *GeneralStat_PlayerWL) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralStat_PlayerWL.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralStat_PlayerWL proto.InternalMessageInfo

func (m *GeneralStat_PlayerWL) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *GeneralStat_PlayerWL) GetWinLoss() *WinLoss {
	if m != nil {
		return m.WinLoss
	}
	return nil
}

type GeneralStats struct {
	GeneralStats         []*GeneralStat `protobuf:"bytes,1,rep,name=general_stats,json=generalStats,proto3" json:"general_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *GeneralStats) Reset()         { *m = GeneralStats{} }
func (m *GeneralStats) String() string { return proto.CompactTextString(m) }
func (*GeneralStats) ProtoMessage()    {}
func (*GeneralStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{8}
}

func (m *GeneralStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GeneralStats.Unmarshal(m, b)
}
func (m *GeneralStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GeneralStats.Marshal(b, m, deterministic)
}
func (m *GeneralStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GeneralStats.Merge(m, src)
}
func (m *GeneralStats) XXX_Size() int {
	return xxx_messageInfo_GeneralStats.Size(m)
}
func (m *GeneralStats) XXX_DiscardUnknown() {
	xxx_messageInfo_GeneralStats.DiscardUnknown(m)
}

var xxx_messageInfo_GeneralStats proto.InternalMessageInfo

func (m *GeneralStats) GetGeneralStats() []*GeneralStat {
	if m != nil {
		return m.GeneralStats
	}
	return nil
}

type Date struct {
	Year                 int32    `protobuf:"varint,1,opt,name=Year,proto3" json:"Year,omitempty"`
	Month                int32    `protobuf:"varint,2,opt,name=Month,proto3" json:"Month,omitempty"`
	Day                  int32    `protobuf:"varint,3,opt,name=Day,proto3" json:"Day,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Date) Reset()         { *m = Date{} }
func (m *Date) String() string { return proto.CompactTextString(m) }
func (*Date) ProtoMessage()    {}
func (*Date) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{9}
}

func (m *Date) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Date.Unmarshal(m, b)
}
func (m *Date) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Date.Marshal(b, m, deterministic)
}
func (m *Date) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Date.Merge(m, src)
}
func (m *Date) XXX_Size() int {
	return xxx_messageInfo_Date.Size(m)
}
func (m *Date) XXX_DiscardUnknown() {
	xxx_messageInfo_Date.DiscardUnknown(m)
}

var xxx_messageInfo_Date proto.InternalMessageInfo

func (m *Date) GetYear() int32 {
	if m != nil {
		return m.Year
	}
	return 0
}

func (m *Date) GetMonth() int32 {
	if m != nil {
		return m.Month
	}
	return 0
}

func (m *Date) GetDay() int32 {
	if m != nil {
		return m.Day
	}
	return 0
}

type TeamStat struct {
	Date                 *Date    `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Team                 Team     `protobuf:"varint,2,opt,name=team,proto3,enum=matches.Team" json:"team,omitempty"`
	Wins                 int32    `protobuf:"varint,3,opt,name=wins,proto3" json:"wins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TeamStat) Reset()         { *m = TeamStat{} }
func (m *TeamStat) String() string { return proto.CompactTextString(m) }
func (*TeamStat) ProtoMessage()    {}
func (*TeamStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{10}
}

func (m *TeamStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStat.Unmarshal(m, b)
}
func (m *TeamStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStat.Marshal(b, m, deterministic)
}
func (m *TeamStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStat.Merge(m, src)
}
func (m *TeamStat) XXX_Size() int {
	return xxx_messageInfo_TeamStat.Size(m)
}
func (m *TeamStat) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStat.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStat proto.InternalMessageInfo

func (m *TeamStat) GetDate() *Date {
	if m != nil {
		return m.Date
	}
	return nil
}

func (m *TeamStat) GetTeam() Team {
	if m != nil {
		return m.Team
	}
	return Team_NONE
}

func (m *TeamStat) GetWins() int32 {
	if m != nil {
		return m.Wins
	}
	return 0
}

type TeamStats struct {
	TeamStats            []*TeamStat `protobuf:"bytes,1,rep,name=team_stats,json=teamStats,proto3" json:"team_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *TeamStats) Reset()         { *m = TeamStats{} }
func (m *TeamStats) String() string { return proto.CompactTextString(m) }
func (*TeamStats) ProtoMessage()    {}
func (*TeamStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{11}
}

func (m *TeamStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamStats.Unmarshal(m, b)
}
func (m *TeamStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamStats.Marshal(b, m, deterministic)
}
func (m *TeamStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamStats.Merge(m, src)
}
func (m *TeamStats) XXX_Size() int {
	return xxx_messageInfo_TeamStats.Size(m)
}
func (m *TeamStats) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamStats.DiscardUnknown(m)
}

var xxx_messageInfo_TeamStats proto.InternalMessageInfo

func (m *TeamStats) GetTeamStats() []*TeamStat {
	if m != nil {
		return m.TeamStats
	}
	return nil
}

type MapStat struct {
	Map                  string   `protobuf:"bytes,1,opt,name=map,proto3" json:"map,omitempty"`
	Team                 Team     `protobuf:"varint,2,opt,name=team,proto3,enum=matches.Team" json:"team,omitempty"`
	Wins                 int32    `protobuf:"varint,3,opt,name=wins,proto3" json:"wins,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MapStat) Reset()         { *m = MapStat{} }
func (m *MapStat) String() string { return proto.CompactTextString(m) }
func (*MapStat) ProtoMessage()    {}
func (*MapStat) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{12}
}

func (m *MapStat) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapStat.Unmarshal(m, b)
}
func (m *MapStat) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapStat.Marshal(b, m, deterministic)
}
func (m *MapStat) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapStat.Merge(m, src)
}
func (m *MapStat) XXX_Size() int {
	return xxx_messageInfo_MapStat.Size(m)
}
func (m *MapStat) XXX_DiscardUnknown() {
	xxx_messageInfo_MapStat.DiscardUnknown(m)
}

var xxx_messageInfo_MapStat proto.InternalMessageInfo

func (m *MapStat) GetMap() string {
	if m != nil {
		return m.Map
	}
	return ""
}

func (m *MapStat) GetTeam() Team {
	if m != nil {
		return m.Team
	}
	return Team_NONE
}

func (m *MapStat) GetWins() int32 {
	if m != nil {
		return m.Wins
	}
	return 0
}

type MapStats struct {
	MapStats             []*MapStat `protobuf:"bytes,1,rep,name=map_stats,json=mapStats,proto3" json:"map_stats,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MapStats) Reset()         { *m = MapStats{} }
func (m *MapStats) String() string { return proto.CompactTextString(m) }
func (*MapStats) ProtoMessage()    {}
func (*MapStats) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{13}
}

func (m *MapStats) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MapStats.Unmarshal(m, b)
}
func (m *MapStats) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MapStats.Marshal(b, m, deterministic)
}
func (m *MapStats) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MapStats.Merge(m, src)
}
func (m *MapStats) XXX_Size() int {
	return xxx_messageInfo_MapStats.Size(m)
}
func (m *MapStats) XXX_DiscardUnknown() {
	xxx_messageInfo_MapStats.DiscardUnknown(m)
}

var xxx_messageInfo_MapStats proto.InternalMessageInfo

func (m *MapStats) GetMapStats() []*MapStat {
	if m != nil {
		return m.MapStats
	}
	return nil
}

type SaveResponse struct {
	Success              bool     `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SaveResponse) Reset()         { *m = SaveResponse{} }
func (m *SaveResponse) String() string { return proto.CompactTextString(m) }
func (*SaveResponse) ProtoMessage()    {}
func (*SaveResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{14}
}

func (m *SaveResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SaveResponse.Unmarshal(m, b)
}
func (m *SaveResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SaveResponse.Marshal(b, m, deterministic)
}
func (m *SaveResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SaveResponse.Merge(m, src)
}
func (m *SaveResponse) XXX_Size() int {
	return xxx_messageInfo_SaveResponse.Size(m)
}
func (m *SaveResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SaveResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SaveResponse proto.InternalMessageInfo

func (m *SaveResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

type Costs struct {
	Player               *Player              `protobuf:"bytes,2,opt,name=player,proto3" json:"player,omitempty"`
	Buildings            []*Costs_BuiltObject `protobuf:"bytes,3,rep,name=buildings,proto3" json:"buildings,omitempty"`
	Units                []*Costs_BuiltObject `protobuf:"bytes,4,rep,name=units,proto3" json:"units,omitempty"`
	Upgrades             []*Costs_BuiltObject `protobuf:"bytes,5,rep,name=upgrades,proto3" json:"upgrades,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *Costs) Reset()         { *m = Costs{} }
func (m *Costs) String() string { return proto.CompactTextString(m) }
func (*Costs) ProtoMessage()    {}
func (*Costs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{15}
}

func (m *Costs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Costs.Unmarshal(m, b)
}
func (m *Costs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Costs.Marshal(b, m, deterministic)
}
func (m *Costs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Costs.Merge(m, src)
}
func (m *Costs) XXX_Size() int {
	return xxx_messageInfo_Costs.Size(m)
}
func (m *Costs) XXX_DiscardUnknown() {
	xxx_messageInfo_Costs.DiscardUnknown(m)
}

var xxx_messageInfo_Costs proto.InternalMessageInfo

func (m *Costs) GetPlayer() *Player {
	if m != nil {
		return m.Player
	}
	return nil
}

func (m *Costs) GetBuildings() []*Costs_BuiltObject {
	if m != nil {
		return m.Buildings
	}
	return nil
}

func (m *Costs) GetUnits() []*Costs_BuiltObject {
	if m != nil {
		return m.Units
	}
	return nil
}

func (m *Costs) GetUpgrades() []*Costs_BuiltObject {
	if m != nil {
		return m.Upgrades
	}
	return nil
}

type Costs_BuiltObject struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Count                int32    `protobuf:"varint,2,opt,name=count,proto3" json:"count,omitempty"`
	TotalSpent           int32    `protobuf:"varint,3,opt,name=total_spent,json=totalSpent,proto3" json:"total_spent,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Costs_BuiltObject) Reset()         { *m = Costs_BuiltObject{} }
func (m *Costs_BuiltObject) String() string { return proto.CompactTextString(m) }
func (*Costs_BuiltObject) ProtoMessage()    {}
func (*Costs_BuiltObject) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{15, 0}
}

func (m *Costs_BuiltObject) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Costs_BuiltObject.Unmarshal(m, b)
}
func (m *Costs_BuiltObject) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Costs_BuiltObject.Marshal(b, m, deterministic)
}
func (m *Costs_BuiltObject) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Costs_BuiltObject.Merge(m, src)
}
func (m *Costs_BuiltObject) XXX_Size() int {
	return xxx_messageInfo_Costs_BuiltObject.Size(m)
}
func (m *Costs_BuiltObject) XXX_DiscardUnknown() {
	xxx_messageInfo_Costs_BuiltObject.DiscardUnknown(m)
}

var xxx_messageInfo_Costs_BuiltObject proto.InternalMessageInfo

func (m *Costs_BuiltObject) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Costs_BuiltObject) GetCount() int32 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Costs_BuiltObject) GetTotalSpent() int32 {
	if m != nil {
		return m.TotalSpent
	}
	return 0
}

type APM struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	ActionCount          int64    `protobuf:"varint,2,opt,name=action_count,json=actionCount,proto3" json:"action_count,omitempty"`
	Minutes              float64  `protobuf:"fixed64,3,opt,name=minutes,proto3" json:"minutes,omitempty"`
	Apm                  float64  `protobuf:"fixed64,4,opt,name=apm,proto3" json:"apm,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *APM) Reset()         { *m = APM{} }
func (m *APM) String() string { return proto.CompactTextString(m) }
func (*APM) ProtoMessage()    {}
func (*APM) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{16}
}

func (m *APM) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_APM.Unmarshal(m, b)
}
func (m *APM) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_APM.Marshal(b, m, deterministic)
}
func (m *APM) XXX_Merge(src proto.Message) {
	xxx_messageInfo_APM.Merge(m, src)
}
func (m *APM) XXX_Size() int {
	return xxx_messageInfo_APM.Size(m)
}
func (m *APM) XXX_DiscardUnknown() {
	xxx_messageInfo_APM.DiscardUnknown(m)
}

var xxx_messageInfo_APM proto.InternalMessageInfo

func (m *APM) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *APM) GetActionCount() int64 {
	if m != nil {
		return m.ActionCount
	}
	return 0
}

func (m *APM) GetMinutes() float64 {
	if m != nil {
		return m.Minutes
	}
	return 0
}

func (m *APM) GetApm() float64 {
	if m != nil {
		return m.Apm
	}
	return 0
}

type UpgradeEvent struct {
	PlayerName           string   `protobuf:"bytes,1,opt,name=player_name,json=playerName,proto3" json:"player_name,omitempty"`
	Timecode             int64    `protobuf:"varint,2,opt,name=timecode,proto3" json:"timecode,omitempty"`
	UpgradeName          string   `protobuf:"bytes,3,opt,name=upgrade_name,json=upgradeName,proto3" json:"upgrade_name,omitempty"`
	Cost                 int64    `protobuf:"varint,4,opt,name=cost,proto3" json:"cost,omitempty"`
	AtMinute             float64  `protobuf:"fixed64,5,opt,name=atMinute,proto3" json:"atMinute,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UpgradeEvent) Reset()         { *m = UpgradeEvent{} }
func (m *UpgradeEvent) String() string { return proto.CompactTextString(m) }
func (*UpgradeEvent) ProtoMessage()    {}
func (*UpgradeEvent) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{17}
}

func (m *UpgradeEvent) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UpgradeEvent.Unmarshal(m, b)
}
func (m *UpgradeEvent) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UpgradeEvent.Marshal(b, m, deterministic)
}
func (m *UpgradeEvent) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UpgradeEvent.Merge(m, src)
}
func (m *UpgradeEvent) XXX_Size() int {
	return xxx_messageInfo_UpgradeEvent.Size(m)
}
func (m *UpgradeEvent) XXX_DiscardUnknown() {
	xxx_messageInfo_UpgradeEvent.DiscardUnknown(m)
}

var xxx_messageInfo_UpgradeEvent proto.InternalMessageInfo

func (m *UpgradeEvent) GetPlayerName() string {
	if m != nil {
		return m.PlayerName
	}
	return ""
}

func (m *UpgradeEvent) GetTimecode() int64 {
	if m != nil {
		return m.Timecode
	}
	return 0
}

func (m *UpgradeEvent) GetUpgradeName() string {
	if m != nil {
		return m.UpgradeName
	}
	return ""
}

func (m *UpgradeEvent) GetCost() int64 {
	if m != nil {
		return m.Cost
	}
	return 0
}

func (m *UpgradeEvent) GetAtMinute() float64 {
	if m != nil {
		return m.AtMinute
	}
	return 0
}

type Upgrades struct {
	Upgrades             []*UpgradeEvent `protobuf:"bytes,1,rep,name=upgrades,proto3" json:"upgrades,omitempty"`
	XXX_NoUnkeyedLiteral struct{}        `json:"-"`
	XXX_unrecognized     []byte          `json:"-"`
	XXX_sizecache        int32           `json:"-"`
}

func (m *Upgrades) Reset()         { *m = Upgrades{} }
func (m *Upgrades) String() string { return proto.CompactTextString(m) }
func (*Upgrades) ProtoMessage()    {}
func (*Upgrades) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{18}
}

func (m *Upgrades) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Upgrades.Unmarshal(m, b)
}
func (m *Upgrades) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Upgrades.Marshal(b, m, deterministic)
}
func (m *Upgrades) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Upgrades.Merge(m, src)
}
func (m *Upgrades) XXX_Size() int {
	return xxx_messageInfo_Upgrades.Size(m)
}
func (m *Upgrades) XXX_DiscardUnknown() {
	xxx_messageInfo_Upgrades.DiscardUnknown(m)
}

var xxx_messageInfo_Upgrades proto.InternalMessageInfo

func (m *Upgrades) GetUpgrades() []*UpgradeEvent {
	if m != nil {
		return m.Upgrades
	}
	return nil
}

type MatchDetails struct {
	MatchId              int64                `protobuf:"varint,1,opt,name=match_id,json=matchId,proto3" json:"match_id,omitempty"`
	Costs                []*Costs             `protobuf:"bytes,2,rep,name=costs,proto3" json:"costs,omitempty"`
	Apms                 []*APM               `protobuf:"bytes,3,rep,name=apms,proto3" json:"apms,omitempty"`
	UpgradeEvents        map[string]*Upgrades `protobuf:"bytes,4,rep,name=upgrade_events,json=upgradeEvents,proto3" json:"upgrade_events,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *MatchDetails) Reset()         { *m = MatchDetails{} }
func (m *MatchDetails) String() string { return proto.CompactTextString(m) }
func (*MatchDetails) ProtoMessage()    {}
func (*MatchDetails) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{19}
}

func (m *MatchDetails) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MatchDetails.Unmarshal(m, b)
}
func (m *MatchDetails) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MatchDetails.Marshal(b, m, deterministic)
}
func (m *MatchDetails) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MatchDetails.Merge(m, src)
}
func (m *MatchDetails) XXX_Size() int {
	return xxx_messageInfo_MatchDetails.Size(m)
}
func (m *MatchDetails) XXX_DiscardUnknown() {
	xxx_messageInfo_MatchDetails.DiscardUnknown(m)
}

var xxx_messageInfo_MatchDetails proto.InternalMessageInfo

func (m *MatchDetails) GetMatchId() int64 {
	if m != nil {
		return m.MatchId
	}
	return 0
}

func (m *MatchDetails) GetCosts() []*Costs {
	if m != nil {
		return m.Costs
	}
	return nil
}

func (m *MatchDetails) GetApms() []*APM {
	if m != nil {
		return m.Apms
	}
	return nil
}

func (m *MatchDetails) GetUpgradeEvents() map[string]*Upgrades {
	if m != nil {
		return m.UpgradeEvents
	}
	return nil
}

type PairWinLoss struct {
	General1             General  `protobuf:"varint,1,opt,name=general1,proto3,enum=matches.General" json:"general1,omitempty"`
	General2             General  `protobuf:"varint,2,opt,name=general2,proto3,enum=matches.General" json:"general2,omitempty"`
	Winloss              *WinLoss `protobuf:"bytes,3,opt,name=winloss,proto3" json:"winloss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairWinLoss) Reset()         { *m = PairWinLoss{} }
func (m *PairWinLoss) String() string { return proto.CompactTextString(m) }
func (*PairWinLoss) ProtoMessage()    {}
func (*PairWinLoss) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{20}
}

func (m *PairWinLoss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairWinLoss.Unmarshal(m, b)
}
func (m *PairWinLoss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairWinLoss.Marshal(b, m, deterministic)
}
func (m *PairWinLoss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairWinLoss.Merge(m, src)
}
func (m *PairWinLoss) XXX_Size() int {
	return xxx_messageInfo_PairWinLoss.Size(m)
}
func (m *PairWinLoss) XXX_DiscardUnknown() {
	xxx_messageInfo_PairWinLoss.DiscardUnknown(m)
}

var xxx_messageInfo_PairWinLoss proto.InternalMessageInfo

func (m *PairWinLoss) GetGeneral1() General {
	if m != nil {
		return m.General1
	}
	return General_USA
}

func (m *PairWinLoss) GetGeneral2() General {
	if m != nil {
		return m.General2
	}
	return General_USA
}

func (m *PairWinLoss) GetWinloss() *WinLoss {
	if m != nil {
		return m.Winloss
	}
	return nil
}

type PairFactionWinLoss struct {
	Faction1             Faction  `protobuf:"varint,1,opt,name=faction1,proto3,enum=matches.Faction" json:"faction1,omitempty"`
	Faction2             Faction  `protobuf:"varint,2,opt,name=faction2,proto3,enum=matches.Faction" json:"faction2,omitempty"`
	Winloss              *WinLoss `protobuf:"bytes,3,opt,name=winloss,proto3" json:"winloss,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PairFactionWinLoss) Reset()         { *m = PairFactionWinLoss{} }
func (m *PairFactionWinLoss) String() string { return proto.CompactTextString(m) }
func (*PairFactionWinLoss) ProtoMessage()    {}
func (*PairFactionWinLoss) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{21}
}

func (m *PairFactionWinLoss) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairFactionWinLoss.Unmarshal(m, b)
}
func (m *PairFactionWinLoss) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairFactionWinLoss.Marshal(b, m, deterministic)
}
func (m *PairFactionWinLoss) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairFactionWinLoss.Merge(m, src)
}
func (m *PairFactionWinLoss) XXX_Size() int {
	return xxx_messageInfo_PairFactionWinLoss.Size(m)
}
func (m *PairFactionWinLoss) XXX_DiscardUnknown() {
	xxx_messageInfo_PairFactionWinLoss.DiscardUnknown(m)
}

var xxx_messageInfo_PairFactionWinLoss proto.InternalMessageInfo

func (m *PairFactionWinLoss) GetFaction1() Faction {
	if m != nil {
		return m.Faction1
	}
	return Faction_ANYUSA
}

func (m *PairFactionWinLoss) GetFaction2() Faction {
	if m != nil {
		return m.Faction2
	}
	return Faction_ANYUSA
}

func (m *PairFactionWinLoss) GetWinloss() *WinLoss {
	if m != nil {
		return m.Winloss
	}
	return nil
}

type PairsWinLosses struct {
	Pairwl               []*PairWinLoss `protobuf:"bytes,1,rep,name=pairwl,proto3" json:"pairwl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *PairsWinLosses) Reset()         { *m = PairsWinLosses{} }
func (m *PairsWinLosses) String() string { return proto.CompactTextString(m) }
func (*PairsWinLosses) ProtoMessage()    {}
func (*PairsWinLosses) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{22}
}

func (m *PairsWinLosses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairsWinLosses.Unmarshal(m, b)
}
func (m *PairsWinLosses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairsWinLosses.Marshal(b, m, deterministic)
}
func (m *PairsWinLosses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairsWinLosses.Merge(m, src)
}
func (m *PairsWinLosses) XXX_Size() int {
	return xxx_messageInfo_PairsWinLosses.Size(m)
}
func (m *PairsWinLosses) XXX_DiscardUnknown() {
	xxx_messageInfo_PairsWinLosses.DiscardUnknown(m)
}

var xxx_messageInfo_PairsWinLosses proto.InternalMessageInfo

func (m *PairsWinLosses) GetPairwl() []*PairWinLoss {
	if m != nil {
		return m.Pairwl
	}
	return nil
}

type PairFactionWinLosses struct {
	Pairwl               []*PairFactionWinLoss `protobuf:"bytes,1,rep,name=pairwl,proto3" json:"pairwl,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *PairFactionWinLosses) Reset()         { *m = PairFactionWinLosses{} }
func (m *PairFactionWinLosses) String() string { return proto.CompactTextString(m) }
func (*PairFactionWinLosses) ProtoMessage()    {}
func (*PairFactionWinLosses) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{23}
}

func (m *PairFactionWinLosses) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PairFactionWinLosses.Unmarshal(m, b)
}
func (m *PairFactionWinLosses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PairFactionWinLosses.Marshal(b, m, deterministic)
}
func (m *PairFactionWinLosses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PairFactionWinLosses.Merge(m, src)
}
func (m *PairFactionWinLosses) XXX_Size() int {
	return xxx_messageInfo_PairFactionWinLosses.Size(m)
}
func (m *PairFactionWinLosses) XXX_DiscardUnknown() {
	xxx_messageInfo_PairFactionWinLosses.DiscardUnknown(m)
}

var xxx_messageInfo_PairFactionWinLosses proto.InternalMessageInfo

func (m *PairFactionWinLosses) GetPairwl() []*PairFactionWinLoss {
	if m != nil {
		return m.Pairwl
	}
	return nil
}

type TeamPairs struct {
	TeamPairs            map[string]*PairsWinLosses       `protobuf:"bytes,1,rep,name=team_pairs,json=teamPairs,proto3" json:"team_pairs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	FactionPairs         map[string]*PairFactionWinLosses `protobuf:"bytes,2,rep,name=faction_pairs,json=factionPairs,proto3" json:"faction_pairs,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}                         `json:"-"`
	XXX_unrecognized     []byte                           `json:"-"`
	XXX_sizecache        int32                            `json:"-"`
}

func (m *TeamPairs) Reset()         { *m = TeamPairs{} }
func (m *TeamPairs) String() string { return proto.CompactTextString(m) }
func (*TeamPairs) ProtoMessage()    {}
func (*TeamPairs) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{24}
}

func (m *TeamPairs) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TeamPairs.Unmarshal(m, b)
}
func (m *TeamPairs) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TeamPairs.Marshal(b, m, deterministic)
}
func (m *TeamPairs) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TeamPairs.Merge(m, src)
}
func (m *TeamPairs) XXX_Size() int {
	return xxx_messageInfo_TeamPairs.Size(m)
}
func (m *TeamPairs) XXX_DiscardUnknown() {
	xxx_messageInfo_TeamPairs.DiscardUnknown(m)
}

var xxx_messageInfo_TeamPairs proto.InternalMessageInfo

func (m *TeamPairs) GetTeamPairs() map[string]*PairsWinLosses {
	if m != nil {
		return m.TeamPairs
	}
	return nil
}

func (m *TeamPairs) GetFactionPairs() map[string]*PairFactionWinLosses {
	if m != nil {
		return m.FactionPairs
	}
	return nil
}

type BaysCondition struct {
	// Types that are valid to be assigned to MapOrPlayer:
	//	*BaysCondition_Map
	//	*BaysCondition_Player
	MapOrPlayer          isBaysCondition_MapOrPlayer `protobuf_oneof:"mapOrPlayer"`
	Team                 Team                        `protobuf:"varint,8,opt,name=team,proto3,enum=matches.Team" json:"team,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *BaysCondition) Reset()         { *m = BaysCondition{} }
func (m *BaysCondition) String() string { return proto.CompactTextString(m) }
func (*BaysCondition) ProtoMessage()    {}
func (*BaysCondition) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{25}
}

func (m *BaysCondition) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BaysCondition.Unmarshal(m, b)
}
func (m *BaysCondition) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BaysCondition.Marshal(b, m, deterministic)
}
func (m *BaysCondition) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BaysCondition.Merge(m, src)
}
func (m *BaysCondition) XXX_Size() int {
	return xxx_messageInfo_BaysCondition.Size(m)
}
func (m *BaysCondition) XXX_DiscardUnknown() {
	xxx_messageInfo_BaysCondition.DiscardUnknown(m)
}

var xxx_messageInfo_BaysCondition proto.InternalMessageInfo

type isBaysCondition_MapOrPlayer interface {
	isBaysCondition_MapOrPlayer()
}

type BaysCondition_Map struct {
	Map string `protobuf:"bytes,2,opt,name=map,proto3,oneof"`
}

type BaysCondition_Player struct {
	Player *Player `protobuf:"bytes,5,opt,name=player,proto3,oneof"`
}

func (*BaysCondition_Map) isBaysCondition_MapOrPlayer() {}

func (*BaysCondition_Player) isBaysCondition_MapOrPlayer() {}

func (m *BaysCondition) GetMapOrPlayer() isBaysCondition_MapOrPlayer {
	if m != nil {
		return m.MapOrPlayer
	}
	return nil
}

func (m *BaysCondition) GetMap() string {
	if x, ok := m.GetMapOrPlayer().(*BaysCondition_Map); ok {
		return x.Map
	}
	return ""
}

func (m *BaysCondition) GetPlayer() *Player {
	if x, ok := m.GetMapOrPlayer().(*BaysCondition_Player); ok {
		return x.Player
	}
	return nil
}

func (m *BaysCondition) GetTeam() Team {
	if m != nil {
		return m.Team
	}
	return Team_NONE
}

// XXX_OneofWrappers is for the internal use of the proto package.
func (*BaysCondition) XXX_OneofWrappers() []interface{} {
	return []interface{}{
		(*BaysCondition_Map)(nil),
		(*BaysCondition_Player)(nil),
	}
}

type BayesResult struct {
	Condition            *BaysCondition `protobuf:"bytes,1,opt,name=condition,proto3" json:"condition,omitempty"`
	Likelyhood           float32        `protobuf:"fixed32,2,opt,name=likelyhood,proto3" json:"likelyhood,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BayesResult) Reset()         { *m = BayesResult{} }
func (m *BayesResult) String() string { return proto.CompactTextString(m) }
func (*BayesResult) ProtoMessage()    {}
func (*BayesResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{26}
}

func (m *BayesResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BayesResult.Unmarshal(m, b)
}
func (m *BayesResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BayesResult.Marshal(b, m, deterministic)
}
func (m *BayesResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BayesResult.Merge(m, src)
}
func (m *BayesResult) XXX_Size() int {
	return xxx_messageInfo_BayesResult.Size(m)
}
func (m *BayesResult) XXX_DiscardUnknown() {
	xxx_messageInfo_BayesResult.DiscardUnknown(m)
}

var xxx_messageInfo_BayesResult proto.InternalMessageInfo

func (m *BayesResult) GetCondition() *BaysCondition {
	if m != nil {
		return m.Condition
	}
	return nil
}

func (m *BayesResult) GetLikelyhood() float32 {
	if m != nil {
		return m.Likelyhood
	}
	return 0
}

type BayesResults struct {
	Results              []*BayesResult `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *BayesResults) Reset()         { *m = BayesResults{} }
func (m *BayesResults) String() string { return proto.CompactTextString(m) }
func (*BayesResults) ProtoMessage()    {}
func (*BayesResults) Descriptor() ([]byte, []int) {
	return fileDescriptor_0aabbed45d0fc8b7, []int{27}
}

func (m *BayesResults) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BayesResults.Unmarshal(m, b)
}
func (m *BayesResults) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BayesResults.Marshal(b, m, deterministic)
}
func (m *BayesResults) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BayesResults.Merge(m, src)
}
func (m *BayesResults) XXX_Size() int {
	return xxx_messageInfo_BayesResults.Size(m)
}
func (m *BayesResults) XXX_DiscardUnknown() {
	xxx_messageInfo_BayesResults.DiscardUnknown(m)
}

var xxx_messageInfo_BayesResults proto.InternalMessageInfo

func (m *BayesResults) GetResults() []*BayesResult {
	if m != nil {
		return m.Results
	}
	return nil
}

func init() {
	proto.RegisterEnum("matches.General", General_name, General_value)
	proto.RegisterEnum("matches.Faction", Faction_name, Faction_value)
	proto.RegisterEnum("matches.Team", Team_name, Team_value)
	proto.RegisterType((*Player)(nil), "matches.Player")
	proto.RegisterType((*MatchInfo)(nil), "matches.MatchInfo")
	proto.RegisterType((*Matches)(nil), "matches.Matches")
	proto.RegisterType((*WinLoss)(nil), "matches.WinLoss")
	proto.RegisterType((*GeneralWL)(nil), "matches.GeneralWL")
	proto.RegisterType((*PlayerStat)(nil), "matches.PlayerStat")
	proto.RegisterType((*PlayerStat_FactionWL)(nil), "matches.PlayerStat.FactionWL")
	proto.RegisterType((*PlayerStats)(nil), "matches.PlayerStats")
	proto.RegisterType((*GeneralStat)(nil), "matches.GeneralStat")
	proto.RegisterType((*GeneralStat_PlayerWL)(nil), "matches.GeneralStat.PlayerWL")
	proto.RegisterType((*GeneralStats)(nil), "matches.GeneralStats")
	proto.RegisterType((*Date)(nil), "matches.Date")
	proto.RegisterType((*TeamStat)(nil), "matches.TeamStat")
	proto.RegisterType((*TeamStats)(nil), "matches.TeamStats")
	proto.RegisterType((*MapStat)(nil), "matches.MapStat")
	proto.RegisterType((*MapStats)(nil), "matches.MapStats")
	proto.RegisterType((*SaveResponse)(nil), "matches.SaveResponse")
	proto.RegisterType((*Costs)(nil), "matches.Costs")
	proto.RegisterType((*Costs_BuiltObject)(nil), "matches.Costs.BuiltObject")
	proto.RegisterType((*APM)(nil), "matches.APM")
	proto.RegisterType((*UpgradeEvent)(nil), "matches.UpgradeEvent")
	proto.RegisterType((*Upgrades)(nil), "matches.Upgrades")
	proto.RegisterType((*MatchDetails)(nil), "matches.MatchDetails")
	proto.RegisterMapType((map[string]*Upgrades)(nil), "matches.MatchDetails.UpgradeEventsEntry")
	proto.RegisterType((*PairWinLoss)(nil), "matches.PairWinLoss")
	proto.RegisterType((*PairFactionWinLoss)(nil), "matches.PairFactionWinLoss")
	proto.RegisterType((*PairsWinLosses)(nil), "matches.PairsWinLosses")
	proto.RegisterType((*PairFactionWinLosses)(nil), "matches.PairFactionWinLosses")
	proto.RegisterType((*TeamPairs)(nil), "matches.TeamPairs")
	proto.RegisterMapType((map[string]*PairFactionWinLosses)(nil), "matches.TeamPairs.FactionPairsEntry")
	proto.RegisterMapType((map[string]*PairsWinLosses)(nil), "matches.TeamPairs.TeamPairsEntry")
	proto.RegisterType((*BaysCondition)(nil), "matches.BaysCondition")
	proto.RegisterType((*BayesResult)(nil), "matches.BayesResult")
	proto.RegisterType((*BayesResults)(nil), "matches.BayesResults")
}

func init() { proto.RegisterFile("proto/match.proto", fileDescriptor_0aabbed45d0fc8b7) }

var fileDescriptor_0aabbed45d0fc8b7 = []byte{
	// 1588 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x57, 0xdd, 0x52, 0x1b, 0x47,
	0x16, 0xf6, 0xe8, 0x77, 0x74, 0x46, 0xe0, 0xa1, 0x97, 0xf5, 0x6a, 0xb5, 0xe5, 0x35, 0x4c, 0xb9,
	0xd6, 0x18, 0xdb, 0xc2, 0x06, 0xaf, 0x7f, 0x92, 0xb2, 0x2b, 0x02, 0x64, 0xa3, 0x32, 0x48, 0x54,
	0x4b, 0x14, 0x26, 0x17, 0xa1, 0x1a, 0xa9, 0x11, 0x13, 0x46, 0x33, 0x2a, 0x75, 0xcb, 0x94, 0xee,
	0x92, 0xcb, 0x3c, 0x40, 0x2a, 0x37, 0xa9, 0x3c, 0x42, 0xde, 0x21, 0x4f, 0x90, 0x57, 0xc9, 0x23,
	0xa4, 0xfa, 0x67, 0x46, 0x33, 0x48, 0x98, 0x90, 0xbb, 0xd3, 0x7d, 0xbe, 0x3e, 0xfd, 0xf5, 0xf9,
	0x9d, 0x81, 0x85, 0xc1, 0x30, 0xe0, 0xc1, 0x5a, 0x9f, 0xf0, 0xce, 0x59, 0x45, 0xca, 0x28, 0x2f,
	0x17, 0x94, 0x95, 0xef, 0xf5, 0x82, 0xa0, 0xe7, 0xd1, 0x35, 0xb9, 0x7d, 0x32, 0x3a, 0x5d, 0xe3,
	0x6e, 0x9f, 0x32, 0x4e, 0xfa, 0x03, 0x85, 0x74, 0xce, 0x21, 0xb7, 0xef, 0x91, 0x31, 0x1d, 0x22,
	0x04, 0x19, 0x9f, 0xf4, 0x69, 0xc9, 0x58, 0x32, 0x56, 0x0a, 0x58, 0xca, 0x68, 0x15, 0xf2, 0x3d,
	0xea, 0xd3, 0x21, 0xf1, 0x4a, 0xa9, 0x25, 0x63, 0x65, 0x7e, 0xdd, 0xae, 0x68, 0xcb, 0x95, 0xf7,
	0x6a, 0x1f, 0x87, 0x00, 0xb4, 0x0c, 0x19, 0x4e, 0x49, 0xbf, 0x94, 0x96, 0xc0, 0xb9, 0x08, 0xd8,
	0xa6, 0xa4, 0x8f, 0xa5, 0xca, 0xf9, 0x2d, 0x05, 0x85, 0x3d, 0xb1, 0x5d, 0xf7, 0x4f, 0x03, 0x34,
	0x0f, 0x29, 0xb7, 0x2b, 0xaf, 0x4b, 0xe3, 0x94, 0xdb, 0x45, 0xaf, 0xa0, 0x10, 0xb1, 0x93, 0xd7,
	0x59, 0xeb, 0xe5, 0x8a, 0xe2, 0x5f, 0x09, 0xf9, 0x57, 0xda, 0x21, 0x02, 0x4f, 0xc0, 0xc8, 0x86,
	0x74, 0x9f, 0x0c, 0xe4, 0xcd, 0x05, 0x2c, 0x44, 0xf4, 0x14, 0x8a, 0x17, 0xae, 0xef, 0xbb, 0x7e,
	0xef, 0x58, 0x92, 0xca, 0xcc, 0x22, 0x65, 0x69, 0x88, 0x58, 0xa0, 0x87, 0x90, 0x1f, 0x48, 0x47,
	0xb0, 0x52, 0x76, 0x29, 0xbd, 0x62, 0xad, 0xdf, 0x8e, 0xc0, 0xca, 0x41, 0x38, 0xd4, 0xa3, 0x87,
	0x60, 0x77, 0x47, 0x43, 0xc2, 0xdd, 0xc0, 0x3f, 0xee, 0xbb, 0xfe, 0x88, 0x53, 0x56, 0xca, 0x2d,
	0x19, 0x2b, 0x06, 0xbe, 0x1d, 0xee, 0xef, 0xa9, 0x6d, 0x54, 0x06, 0xf3, 0xd4, 0xf5, 0xa8, 0x74,
	0x6c, 0x5e, 0xd2, 0x8b, 0xd6, 0xe8, 0xbf, 0x00, 0xae, 0xdf, 0x09, 0xfa, 0x03, 0x8f, 0x72, 0x5a,
	0x32, 0xa5, 0x36, 0xb6, 0x83, 0x16, 0x21, 0xeb, 0x07, 0xc2, 0x76, 0x41, 0xaa, 0xd4, 0xc2, 0x79,
	0x09, 0xf9, 0x3d, 0xc5, 0x0b, 0x3d, 0x86, 0x30, 0xce, 0x25, 0x43, 0x52, 0x46, 0x11, 0xe5, 0xc8,
	0xcb, 0x38, 0x84, 0x38, 0xff, 0x87, 0xfc, 0xa1, 0xeb, 0xef, 0x06, 0x8c, 0x89, 0x50, 0x5f, 0xb8,
	0x3e, 0x93, 0xbe, 0xcf, 0x62, 0x29, 0xa3, 0x3b, 0x90, 0xf3, 0x02, 0xc6, 0x28, 0x93, 0xae, 0xcf,
	0x62, 0xbd, 0x72, 0xba, 0x50, 0xd0, 0xa1, 0x3e, 0xdc, 0x8d, 0xe7, 0x83, 0x71, 0x5d, 0x3e, 0x3c,
	0x02, 0xf3, 0xc2, 0xf5, 0x8f, 0x85, 0x19, 0x1d, 0xcd, 0x09, 0x58, 0x13, 0xc1, 0xf9, 0x0b, 0x25,
	0x38, 0xdf, 0xa7, 0x00, 0x94, 0x9b, 0x5b, 0x9c, 0x70, 0x74, 0x0f, 0x2c, 0xe5, 0xec, 0xe3, 0x58,
	0x4a, 0x82, 0xda, 0x6a, 0x08, 0xdf, 0xad, 0x40, 0x96, 0x71, 0xc2, 0x85, 0xe5, 0xe4, 0xc3, 0x23,
	0xae, 0x58, 0x01, 0xd0, 0x26, 0xcc, 0x9d, 0x92, 0x8e, 0x8c, 0x95, 0x3a, 0x91, 0x96, 0x27, 0xee,
	0x5e, 0x8a, 0xae, 0xb8, 0xb6, 0xf2, 0x4e, 0x01, 0x0f, 0x77, 0x71, 0x51, 0x9f, 0x11, 0xdb, 0xac,
	0xdc, 0x85, 0x42, 0xa4, 0x12, 0x3e, 0xd0, 0xca, 0x29, 0x1f, 0x68, 0x10, 0x0e, 0x01, 0x37, 0xf3,
	0x41, 0x0d, 0xac, 0x09, 0x17, 0x86, 0x5e, 0x40, 0x51, 0xfb, 0x40, 0xf1, 0x56, 0x21, 0xfe, 0xc7,
	0x0c, 0xde, 0x58, 0x3b, 0x4b, 0x9e, 0x73, 0xfe, 0x30, 0xc0, 0xd2, 0x5e, 0x90, 0xbe, 0xbc, 0x49,
	0xcc, 0x36, 0x92, 0x6e, 0xbd, 0x7b, 0x19, 0x29, 0xbd, 0xa4, 0x2e, 0x9e, 0x78, 0xf8, 0x7f, 0x90,
	0xe5, 0x01, 0x27, 0x9e, 0xac, 0xbf, 0x59, 0x2f, 0x54, 0xea, 0xf2, 0x47, 0x30, 0xc3, 0xa3, 0xd7,
	0x07, 0xf8, 0x46, 0x9e, 0xab, 0x43, 0x31, 0x46, 0x90, 0xa1, 0xd7, 0x30, 0xa7, 0x5f, 0x94, 0xf0,
	0xdd, 0xe2, 0xac, 0xe7, 0xe0, 0x62, 0x2f, 0x76, 0xd4, 0xd9, 0x84, 0xcc, 0x36, 0xe1, 0x54, 0x94,
	0xc8, 0x11, 0x25, 0xc3, 0xb0, 0x44, 0x84, 0x2c, 0x0a, 0x72, 0x2f, 0xf0, 0xf9, 0x99, 0xae, 0x10,
	0xb5, 0x10, 0xcd, 0x67, 0x9b, 0x8c, 0xe5, 0xe3, 0xb3, 0x58, 0x88, 0x4e, 0x17, 0x4c, 0xd1, 0x52,
	0xa4, 0xf7, 0x97, 0x21, 0xd3, 0x25, 0x5c, 0xbd, 0xd0, 0x8a, 0x35, 0x20, 0x71, 0x09, 0x96, 0xaa,
	0xa8, 0x71, 0xa6, 0xae, 0x6c, 0x9c, 0x51, 0xc1, 0xa6, 0x27, 0x05, 0xeb, 0xbc, 0x81, 0x42, 0x78,
	0x0b, 0x43, 0x4f, 0x01, 0x04, 0x30, 0xf1, 0xdc, 0x85, 0x84, 0x25, 0xf9, 0xd6, 0x02, 0x0f, 0x4f,
	0x38, 0x58, 0xf4, 0x91, 0x81, 0xe4, 0xa8, 0xdb, 0xa7, 0x31, 0x69, 0x9f, 0x7f, 0x93, 0xd2, 0x6b,
	0x30, 0xb5, 0x4d, 0x86, 0x9e, 0x40, 0xa1, 0x4f, 0x06, 0x09, 0x42, 0x76, 0xac, 0x3d, 0x49, 0x14,
	0x36, 0xfb, 0x1a, 0xee, 0xac, 0x40, 0xb1, 0x45, 0x3e, 0x51, 0x4c, 0xd9, 0x20, 0xf0, 0x19, 0x45,
	0x25, 0xc8, 0xb3, 0x51, 0xa7, 0x43, 0x99, 0xea, 0x52, 0x26, 0x0e, 0x97, 0xce, 0xaf, 0x29, 0xc8,
	0x6e, 0x05, 0x8c, 0x33, 0xf4, 0x00, 0x72, 0x2a, 0x63, 0x74, 0x86, 0x4c, 0x75, 0x6c, 0xad, 0x16,
	0x93, 0xe5, 0x64, 0xe4, 0x7a, 0x5d, 0xd7, 0xef, 0x85, 0xf5, 0x5f, 0x8e, 0xb0, 0xd2, 0x56, 0x65,
	0x73, 0xe4, 0x7a, 0xbc, 0x79, 0xf2, 0x2d, 0xed, 0x70, 0x3c, 0x01, 0xa3, 0xa7, 0x90, 0x1d, 0xf9,
	0x2e, 0x67, 0xa5, 0xcc, 0xb5, 0xa7, 0x14, 0x10, 0xbd, 0x00, 0x73, 0x34, 0xe8, 0x0d, 0x49, 0x97,
	0x86, 0x83, 0xe4, 0x73, 0x87, 0x22, 0x6c, 0xf9, 0x23, 0x58, 0x31, 0xc5, 0xcc, 0x69, 0xbc, 0x08,
	0xd9, 0x4e, 0x30, 0xf2, 0x79, 0x98, 0x7f, 0x72, 0x21, 0x4a, 0x49, 0xd6, 0xd7, 0x31, 0x1b, 0x50,
	0x9f, 0xeb, 0x78, 0x80, 0xdc, 0x6a, 0x89, 0x1d, 0x67, 0x04, 0xe9, 0xea, 0xfe, 0xde, 0xf5, 0x25,
	0xb7, 0x0c, 0x45, 0xdd, 0x28, 0x27, 0xb7, 0xa4, 0xb1, 0xa5, 0xf6, 0xb6, 0xe4, 0x5d, 0x25, 0xc8,
	0x87, 0x03, 0x2f, 0x2d, 0x07, 0x5e, 0xb8, 0x14, 0x39, 0x44, 0x06, 0x6a, 0xce, 0x1a, 0x58, 0x88,
	0xce, 0x2f, 0x06, 0x14, 0x0f, 0xd4, 0xeb, 0x6a, 0x9f, 0xa8, 0xff, 0x17, 0x9a, 0x7a, 0x19, 0x4c,
	0x31, 0xd3, 0x3b, 0x41, 0x97, 0xea, 0xcb, 0xa3, 0xb5, 0x20, 0xa7, 0x5d, 0xa5, 0x4e, 0xab, 0x59,
	0x6f, 0xe9, 0x3d, 0x79, 0x1c, 0x41, 0xa6, 0x13, 0x30, 0x2e, 0x39, 0xa4, 0xb1, 0x94, 0x85, 0x49,
	0xc2, 0xd5, 0x30, 0x2e, 0x65, 0x25, 0xb7, 0x68, 0xed, 0xbc, 0x01, 0x53, 0xf3, 0x63, 0xe8, 0x59,
	0x2c, 0x6a, 0x2a, 0x59, 0xff, 0x19, 0x45, 0x2d, 0xfe, 0x88, 0x49, 0xc0, 0x9c, 0x9f, 0x52, 0x50,
	0x94, 0x63, 0x76, 0x9b, 0x72, 0xe2, 0x7a, 0x0c, 0xfd, 0x1b, 0x4c, 0x79, 0xe4, 0x38, 0xfa, 0xaa,
	0x51, 0xb3, 0xb7, 0xde, 0x45, 0xf7, 0x45, 0xe4, 0x58, 0xd4, 0x57, 0xe7, 0x93, 0x19, 0x81, 0x95,
	0x12, 0x2d, 0x41, 0x86, 0x0c, 0xfa, 0x61, 0x86, 0x16, 0x23, 0x50, 0x75, 0x7f, 0x0f, 0x4b, 0x0d,
	0x6a, 0xc2, 0x7c, 0xe8, 0x05, 0x2a, 0xe8, 0x84, 0x79, 0xb9, 0x92, 0x1c, 0xfc, 0x9a, 0x51, 0x82,
	0x39, 0xab, 0xf9, 0x7c, 0x38, 0xc6, 0x73, 0xa3, 0xf8, 0x5e, 0xb9, 0x05, 0x68, 0x1a, 0x24, 0x82,
	0x79, 0x4e, 0xc7, 0x61, 0x43, 0x38, 0xa7, 0x63, 0xf4, 0x00, 0xb2, 0x9f, 0x88, 0x37, 0xa2, 0xba,
	0xd2, 0x16, 0x2e, 0x3b, 0x87, 0x61, 0xa5, 0xff, 0x22, 0xf5, 0xca, 0x70, 0x7e, 0x34, 0xc0, 0xda,
	0x27, 0xee, 0x30, 0xfc, 0xdc, 0x78, 0x0c, 0xa6, 0xee, 0xb1, 0xcf, 0xae, 0x1c, 0x41, 0x11, 0x22,
	0x86, 0x5e, 0xbf, 0xf2, 0xa3, 0x33, 0x42, 0x88, 0xe9, 0x76, 0xe1, 0xfa, 0x72, 0x4c, 0xa4, 0x3f,
	0x33, 0x26, 0x04, 0xc0, 0xf9, 0xd9, 0x00, 0x24, 0x78, 0x85, 0xb3, 0x7c, 0x42, 0x4f, 0xcf, 0xeb,
	0x67, 0x57, 0x4e, 0xf4, 0x08, 0x11, 0x43, 0x4f, 0xd3, 0xbb, 0x8c, 0xbe, 0x19, 0xbd, 0xb7, 0x30,
	0x2f, 0xd8, 0x31, 0xad, 0x90, 0x1f, 0x78, 0xb9, 0x01, 0x71, 0x87, 0x17, 0xde, 0xd4, 0x00, 0x8b,
	0xb9, 0x17, 0x6b, 0x8c, 0xf3, 0x01, 0x16, 0xa7, 0x5f, 0x47, 0x19, 0xda, 0xb8, 0x64, 0xe5, 0x3f,
	0x09, 0x2b, 0x49, 0x78, 0x64, 0xec, 0xf7, 0x94, 0x1a, 0x2f, 0x92, 0x11, 0xfa, 0x4a, 0x8f, 0x17,
	0xa1, 0x0c, 0x0b, 0x64, 0x39, 0x31, 0x15, 0x24, 0x6e, 0x22, 0xa9, 0x64, 0x93, 0xe3, 0x46, 0x59,
	0xa8, 0x4f, 0x3e, 0xc3, 0x94, 0x11, 0x55, 0x09, 0xf7, 0x67, 0x18, 0xd1, 0x8c, 0x62, 0x76, 0xc2,
	0xaf, 0x31, 0xb9, 0x55, 0x3e, 0x80, 0xf9, 0xe4, 0x3d, 0x33, 0xf2, 0xf5, 0x49, 0x32, 0x5f, 0xff,
	0x95, 0x78, 0xf2, 0xc4, 0xc3, 0xb1, 0xac, 0x2d, 0x7f, 0x03, 0x0b, 0x53, 0x37, 0xcf, 0xb0, 0xbc,
	0x91, 0xb4, 0x7c, 0xf7, 0x33, 0xce, 0x4c, 0x56, 0xc5, 0x77, 0x06, 0xcc, 0x6d, 0x92, 0x31, 0xdb,
	0x0a, 0xfc, 0xae, 0x2b, 0xbf, 0x0e, 0x91, 0x9a, 0xbb, 0xc2, 0x50, 0x61, 0xe7, 0x96, 0x9a, 0xbc,
	0x0f, 0xa3, 0x99, 0x96, 0x9d, 0x39, 0xd3, 0x76, 0x6e, 0x45, 0x53, 0x2d, 0x1c, 0xd2, 0xe6, 0x95,
	0x43, 0x7a, 0x73, 0x0e, 0xac, 0x3e, 0x19, 0x34, 0x87, 0xea, 0xac, 0xd3, 0x01, 0x6b, 0x93, 0x8c,
	0x29, 0xc3, 0x94, 0x8d, 0x3c, 0x8e, 0x9e, 0x43, 0xa1, 0x13, 0x92, 0xd1, 0x1f, 0x28, 0x77, 0x22,
	0x2b, 0x09, 0xaa, 0x78, 0x02, 0x14, 0xbf, 0x2d, 0x9e, 0x7b, 0x4e, 0xbd, 0xf1, 0x59, 0x10, 0x74,
	0x25, 0xf9, 0x14, 0x8e, 0xed, 0x38, 0x6f, 0xa1, 0x18, 0xbb, 0x84, 0xa1, 0x0a, 0xe4, 0x87, 0x4a,
	0x9c, 0xca, 0xe2, 0x18, 0x0e, 0x87, 0xa0, 0xd5, 0x1f, 0x0c, 0xc8, 0xeb, 0x3a, 0x47, 0x79, 0x48,
	0x1f, 0xb4, 0xaa, 0xf6, 0x2d, 0x21, 0x54, 0xeb, 0xd8, 0x36, 0x50, 0x01, 0xb2, 0xbb, 0xd5, 0x56,
	0x0d, 0xdb, 0x29, 0x21, 0xb6, 0x0e, 0xf6, 0x6b, 0xd8, 0x4e, 0x0b, 0x71, 0x6b, 0xa7, 0xde, 0xa8,
	0xda, 0x19, 0x64, 0x42, 0xa6, 0x71, 0xf0, 0xa1, 0x66, 0x67, 0x85, 0xd4, 0xae, 0x36, 0x3e, 0xd8,
	0x39, 0x54, 0x04, 0xb3, 0xde, 0x78, 0x57, 0x6d, 0xb4, 0xf1, 0x91, 0x9d, 0x17, 0xb6, 0xde, 0xef,
	0x56, 0x6d, 0x53, 0x9c, 0x6a, 0x37, 0x3f, 0xd6, 0x1b, 0x76, 0x01, 0x59, 0x90, 0x6f, 0xb5, 0x6b,
	0xd5, 0xdd, 0xf6, 0x8e, 0x0d, 0xe2, 0xe0, 0x76, 0x6d, 0xaf, 0x69, 0x5b, 0xab, 0x6b, 0x90, 0xd7,
	0x21, 0x45, 0x00, 0xb9, 0x6a, 0xe3, 0x48, 0xb1, 0x29, 0x82, 0x59, 0x6d, 0x1c, 0xa9, 0x1b, 0x0d,
	0xad, 0x11, 0x26, 0x53, 0xab, 0x2f, 0x21, 0x23, 0xff, 0x26, 0x05, 0x8b, 0x66, 0xa3, 0xa6, 0x98,
	0x0b, 0xc1, 0x10, 0x42, 0xfb, 0xb0, 0xa9, 0x78, 0xb7, 0x77, 0x70, 0xad, 0x66, 0xa7, 0x05, 0xec,
	0x5d, 0xf3, 0x00, 0xdb, 0x99, 0xcd, 0x27, 0x5f, 0x3f, 0xea, 0xb9, 0xfc, 0x6c, 0x74, 0x52, 0xe9,
	0x04, 0xfd, 0xb5, 0xd3, 0xe7, 0x67, 0xe3, 0x35, 0xdd, 0xe3, 0x98, 0xfc, 0x84, 0xfa, 0x32, 0xb1,
	0x3a, 0xc9, 0xc9, 0x1f, 0xe2, 0x8d, 0x3f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x60, 0x83, 0x21, 0xc6,
	0xfc, 0x0f, 0x00, 0x00,
}
